name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: self-hosted

    steps:
    - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '7.2'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: PHP Lint
      # You may pin to the exact commit or the version.
      # uses: michaelw90/PHP-Lint@0d9e19434b05c780f6cc87fa573bbc6061dbfe24
      uses: michaelw90/PHP-Lint@2.1.0
    - name: php-codesniffer
      # You may pin to the exact commit or the version.
      # uses: pipeline-components/php-codesniffer@e3341450afba37fab4275b31f041646a26b2da9d
      uses: pipeline-components/php-codesniffer@v0.12.3
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
